apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yelb-db-pvc
  namespace: yelb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
  namespace: yelb
  labels:
    app: yelb-db
    tier: backenddb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yelb-db
      tier: backenddb
  template:
    metadata:
      labels:
        app: yelb-db
        tier: backenddb
    spec:
      containers:
        - name: yelb-db
          image: mreferre/yelb-db:0.6
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: yelb-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: yelb-db-storage
          persistentVolumeClaim:
            claimName: yelb-db-pvc



---
apiVersion: v1
kind: Service
metadata:
  name: yelb-db
  namespace: yelb
  labels:
    app: yelb-db
    tier: backenddb
spec:
  type: ClusterIP
  selector:
    app: yelb-db
    tier: backenddb
  ports:
    - port: 5432
      targetPort: 5432